In [66]:
import numpy as np 
import pandas as pd
np.random.seed(42)

n = 8
random_matrix = np.random.randint(1,10, (n,n))
random_matrix
# index = np.random.choice(random_matrix.size, 10, replace = False)
# print(f"index {index}")
# print(f"Flattens the matrix: {random_matrix.ravel()}")

# random_matrix = random_matrix*1.0 # to convert it to float as np.nan is float
# random_matrix.ravel()[index] = None # returns contiguous flattened array
# # numeric containers always use NaN 
# print(random_matrix)

array([[7, 4, 8, 5, 7, 3, 7, 8],
       [5, 4, 8, 8, 3, 6, 5, 2],
       [8, 6, 2, 5, 1, 6, 9, 1],
       [3, 7, 4, 9, 3, 5, 3, 7],
       [5, 9, 7, 2, 4, 9, 2, 9],
       [5, 2, 4, 7, 8, 3, 1, 4],
       [2, 8, 4, 2, 6, 6, 4, 6],
       [2, 2, 4, 8, 7, 9, 8, 5]])

In [67]:
index = np.random.choice(random_matrix.size, 10, replace = False)
print(f"index {index}")
print(f"Flattens the matrix: {random_matrix.ravel()}")

random_matrix = random_matrix*1.0 # to convert it to float as np.nan is float
random_matrix.ravel()[index] = None # returns contiguous flattened array
# numeric containers always use NaN 
print(random_matrix)

index [21 20 36  3  5 29 12 37 41 33]
Flattens the matrix: [7 4 8 5 7 3 7 8 5 4 8 8 3 6 5 2 8 6 2 5 1 6 9 1 3 7 4 9 3 5 3 7 5 9 7 2 4
 9 2 9 5 2 4 7 8 3 1 4 2 8 4 2 6 6 4 6 2 2 4 8 7 9 8 5]
[[ 7.  4.  8. nan  7. nan  7.  8.]
 [ 5.  4.  8.  8. nan  6.  5.  2.]
 [ 8.  6.  2.  5. nan nan  9.  1.]
 [ 3.  7.  4.  9.  3. nan  3.  7.]
 [ 5. nan  7.  2. nan nan  2.  9.]
 [ 5. nan  4.  7.  8.  3.  1.  4.]
 [ 2.  8.  4.  2.  6.  6.  4.  6.]
 [ 2.  2.  4.  8.  7.  9.  8.  5.]]


In [68]:
scores = pd.DataFrame(random_matrix, index=[f"Player {i}" for i in range(1, n+1)], columns=[f"Round {i}" for i in range(1,n+1)])
scores

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1      7.0      4.0      8.0      NaN      7.0      NaN      7.0   
Player 2      5.0      4.0      8.0      8.0      NaN      6.0      5.0   
Player 3      8.0      6.0      2.0      5.0      NaN      NaN      9.0   
Player 4      3.0      7.0      4.0      9.0      3.0      NaN      3.0   
Player 5      5.0      NaN      7.0      2.0      NaN      NaN      2.0   
Player 6      5.0      NaN      4.0      7.0      8.0      3.0      1.0   
Player 7      2.0      8.0      4.0      2.0      6.0      6.0      4.0   
Player 8      2.0      2.0      4.0      8.0      7.0      9.0      8.0   

          Round 8  
Player 1      8.0  
Player 2      2.0  
Player 3      1.0  
Player 4      7.0  
Player 5      9.0  
Player 6      4.0  
Player 7      6.0  
Player 8      5.0

## Missing data

There are different types of missing data:

None - Pythonic missing data. A Python object - operations done on Python level and not numpy or pandas.
Error when performing arithmetic on None dtypes
NaN - floating point "Not a Number". Supports fast operations, however all arithmetic operations with NaN results in a NaN
NA - pd.NA -> missing indicator that can be used consistently across data types
Pandas treats NaN and None almost interchangeably

isnull() - returns true if value is null
notnull() - returns true if value is not null
dropna() - drops the the whole axis with nulls
fillna() - fills the null values with certain value

In [74]:
scores.isnull()

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1    False    False    False     True    False     True    False   
Player 2    False    False    False    False     True    False    False   
Player 3    False    False    False    False     True     True    False   
Player 4    False    False    False    False    False     True    False   
Player 5    False     True    False    False     True     True    False   
Player 6    False     True    False    False    False    False    False   
Player 7    False    False    False    False    False    False    False   
Player 8    False    False    False    False    False    False    False   

          Round 8  
Player 1    False  
Player 2    False  
Player 3    False  
Player 4    False  
Player 5    False  
Player 6    False  
Player 7    False  
Player 8    False

In [70]:
scores.notnull()

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1     True     True     True    False     True    False     True   
Player 2     True     True     True     True    False     True     True   
Player 3     True     True     True     True    False    False     True   
Player 4     True     True     True     True     True    False     True   
Player 5     True    False     True     True    False    False     True   
Player 6     True    False     True     True     True     True     True   
Player 7     True     True     True     True     True     True     True   
Player 8     True     True     True     True     True     True     True   

          Round 8  
Player 1     True  
Player 2     True  
Player 3     True  
Player 4     True  
Player 5     True  
Player 6     True  
Player 7     True  
Player 8     True

In [71]:
scores.notna()

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1     True     True     True    False     True    False     True   
Player 2     True     True     True     True    False     True     True   
Player 3     True     True     True     True    False    False     True   
Player 4     True     True     True     True     True    False     True   
Player 5     True    False     True     True    False    False     True   
Player 6     True    False     True     True     True     True     True   
Player 7     True     True     True     True     True     True     True   
Player 8     True     True     True     True     True     True     True   

          Round 8  
Player 1     True  
Player 2     True  
Player 3     True  
Player 4     True  
Player 5     True  
Player 6     True  
Player 7     True  
Player 8     True

In [72]:
scores.dropna()

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 7      2.0      8.0      4.0      2.0      6.0      6.0      4.0   
Player 8      2.0      2.0      4.0      8.0      7.0      9.0      8.0   

          Round 8  
Player 7      6.0  
Player 8      5.0

In [75]:
scores.dropna(axis=1)

Round 1  Round 3  Round 7  Round 8
Player 1      7.0      8.0      7.0      8.0
Player 2      5.0      8.0      5.0      2.0
Player 3      8.0      2.0      9.0      1.0
Player 4      3.0      4.0      3.0      7.0
Player 5      5.0      7.0      2.0      9.0
Player 6      5.0      4.0      1.0      4.0
Player 7      2.0      4.0      4.0      6.0
Player 8      2.0      4.0      8.0      5.0