# Python fundamentals part 2

## Error handling
- syntax error
- runtime errors (exceptions)
- semantic errors (logical errors) 

#### syntax error

In [ ]:
prin("hello world")
# Name error, when a variable or function that has not been defined or is not accessible in the current scope

NameError: name 'prin' is not defined

#### runtime error

In [4]:
numbers = list(range(5))
numbers

[0, 1, 2, 3, 4]

In [ ]:
numbers[5]
# Index error, your code is trying to access an index that is invalid

IndexError: list index out of range

#### Logical error

In [ ]:
import numpy as np

radius = 5
# This is not the way to calculate area of a circel
area_circle = np.pi*radius
print(f"{area_circle = :.2f}")

# Even with no crashing, this has a error
# Logical errors occurs when the program runs without crashing, but produces an incorrect result

area_circle = 15.71


### try-except

Try and Except statement is used to handle these errors within our code in Python. The try block is used to check some code for errors i.e the code inside the try block will execute when there is no error in the program. Whereas the code inside the except block will execute whenever the program encounters some error in the preceding try block.

In [15]:

age = float(input("Enter your age: "))
if not 0 <= age <= 125:
  raise ValueError("Age must be between 0 and 125")
print(f"You are {age} years old") 

ValueError: Age must be between 0 and 125

In [16]:

try :
     age = float(input("Enter your age: "))
     if not 0 <= age <= 125:
        raise ValueError("Age must be between 0 and 125")
     print(f"You are {age} years old")
except ValueError as Nope:
    print(Nope) 

Age must be between 0 and 125


In [17]:
while True:
    try :
        age = float(input("Enter your age: "))
        if not 0 <= age <= 125:
            raise ValueError("Age must be between 0 and 125")
        print(f"You are {age} years old")
        break
    except ValueError as Nope:
        print(Nope) 

You are 54.0 years old


## Function

Python Functions is a block of statements that return the specific task

The idea is to put some commonly or repeatedly done tasks together and call the function to reuse the code inside the function to complete common task.
- Increase Code Readability 
- Increase Code Reusability

In [22]:
def squarer(x):
    return x**2

squarer(-3)

9

In [23]:
[squarer(x) for x in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [26]:
def smallest(num1, num2):
    if num1 > num2:
        return num1
    return num2

smallest(3, 5), smallest(7, 7.1), smallest(-4, -8)

(5, 7.1, -4)

#### Default value

In [27]:
def draw_ascii_pattern(number_rows = 5):
    for i in range(1, number_rows + 1):
        print(i * 'x' + (number_rows-i)*'o')

draw_ascii_pattern()

xoooo
xxooo
xxxoo
xxxxo
xxxxx


In [29]:
draw_ascii_pattern(9)

xoooooooo
xxooooooo
xxxoooooo
xxxxooooo
xxxxxoooo
xxxxxxooo
xxxxxxxoo
xxxxxxxxo
xxxxxxxxx


#### Arbitrary arguments, \*args

In [33]:
def my_mean(*args):
    sum_= 0
    for arg in args:
        sum_ += arg
    return sum_/len(args)

my_mean(1,2,3,4)

2.5

In [34]:
def my_mean(*args):
    sum_= 1
    for arg in args:
        sum_ += arg
    return sum_/len(args)

my_mean(1,2,3,4)

2.75

#### Keyword arguments \*\*kwargs

In [39]:
import numpy as np

def simulate_dices(throw=1, dices=2):
    print(np.random.randint(1,7, (throw, dices)))

simulate_dices()

[[6 1]]


In [41]:
simulate_dices(throw=4, dices=3)

[[5 6 1]
 [4 1 2]
 [3 2 2]
 [2 1 3]]


In [42]:
simulate_dices(4,3)

[[3 3 5]
 [5 4 4]
 [1 2 3]
 [6 6 6]]


In [44]:
simulate_dices(dices=3, throw=4)

[[6 6 4]
 [6 2 5]
 [3 6 5]
 [1 1 6]]
